# Generated by Django 4.0 on 2022-10-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_view_user_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
    ]
